<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->unique();
            $table->longText('description')->nullable();
            $table->decimal('price', 10, 2);
            $table->unsignedBigInteger('category_id');
            $table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
            $table->string('image')->nullable();
            $table->boolean('is_active')->default(true);
            $table->integer('stock')->default(0);
            $table->string('sku')->unique()->nullable();
            $table->string('meta_title')->nullable();
            $table->string('meta_description')->nullable();
            $table->string('meta_keywords')->nullable();
            $table->string('meta_image')->nullable();
            $table->timestamps();
            // $table->boolean('is_featured')->default(false);
            // $table->boolean('is_new')->default(false);
            // $table->boolean('is_popular')->default(false);
            // $table->boolean('is_discounted')->default(false);
            // $table->decimal('discount_price', 10, 2)->nullable();
            // $table->dateTime('available_from')->nullable();
            // $table->dateTime('available_to')->nullable();
            // $table->string('brand')->nullable();
            // $table->string('model')->nullable();
            // $table->string('color')->nullable();
            // $table->string('size')->nullable();
            // $table->text('additional_info')->nullable();
            // $table->text('specifications')->nullable();
            // $table->text('warranty_info')->nullable();
            // $table->text('return_policy')->nullable();
            // $table->text('shipping_info')->nullable();
            // $table->text('care_instructions')->nullable();
            // $table->text('usage_instructions')->nullable();
            // $table->text('ingredients')->nullable();
            // $table->text('nutrition_facts')->nullable();
            // $table->text('safety_warnings')->nullable();
            // $table->text('certifications')->nullable();
            // $table->text('reviews')->nullable();
            // $table->text('faqs')->nullable();
            // $table->text('related_products')->nullable();
            // $table->text('cross_sell_products')->nullable();
            // $table->text('up_sell_products')->nullable();
            // $table->text('bundle_products')->nullable();
            // $table->text('gift_card_info')->nullable();
            // $table->text('subscription_info')->nullable();
            // $table->text('pre_order_info')->nullable();
            // $table->text('back_order_info')->nullable();
            // $table->text('limited_edition_info')->nullable();
            // $table->text('exclusive_offers')->nullable();
            // $table->text('loyalty_program_info')->nullable();
            // $table->text('affiliate_program_info')->nullable();
            // $table->text('bulk_order_info')->nullable();
            // $table->text('wholesale_info')->nullable();
            // $table->text('gift_wrapping_info')->nullable();
            // $table->text('customization_options')->nullable();
            // $table->text('personalization_options')->nullable();
            // $table->text('installation_services')->nullable();
            // $table->text('financing_options')->nullable();
            // $table->text('trade_in_program_info')->nullable();
            // $table->text('loyalty_rewards')->nullable();
            // $table->text('referral_program_info')->nullable();
            // $table->text('customer_support_info')->nullable();
            // $table->text('warranty_claim_info')->nullable();
            // $table->text('product_registration_info')->nullable();
            // $table->text('product_recalls')->nullable();
            // $table->text('sustainability_info')->nullable();
            // $table->text('eco_friendly_certifications')->nullable();
            // $table->text('carbon_footprint_info')->nullable();
            // $table->text('recycling_program_info')->nullable();
            // $table->text('energy_efficiency_info')->nullable();
            // $table->text('water_usage_info')->nullable();
            // $table->text('supply_chain_transparency')->nullable();
            // $table->text('ethical_sourcing_info')->nullable();
            // $table->text('community_support_info')->nullable();
            // $table->text('charity_partnerships')->nullable();
            // $table->text('social_responsibility_info')->nullable();
            // $table->text('diversity_inclusion_info')->nullable();
            // $table->text('employee_wellbeing_info')->nullable();
            // $table->text('customer_feedback')->nullable();
            // $table->text('product_updates')->nullable();
            // $table->text('product_variants')->nullable();
            // $table->text('product_tags')->nullable();
            // $table->text('product_attributes')->nullable();
            // $table->text('product_categories')->nullable();
            // $table->text('product_collections')->nullable();
            // $table->text('product_bundles')->nullable();
            // $table->text('product_kits')->nullable();
            // $table->text('product_sets')->nullable();
            // $table->text('product_series')->nullable();
            // $table->text('product_lines')->nullable();
            // $table->text('product_ranges')->nullable();
            // $table->text('product_styles')->nullable();
            // $table->text('product_themes')->nullable();
            // $table->text('product_seasons')->nullable();
            // $table->text('product_trends')->nullable();
            // $table->text('product_inspirations')->nullable();
            // $table->text('product_looks')->nullable();
            // $table->text('product_outfits')->nullable();
            // $table->text('product_combinations')->nullable();
            // $table->text('product_pairings')->nullable();
            // $table->text('product_accessories')->nullable();
            // $table->text('product_add_ons')->nullable();
            // $table->text('product_complements')->nullable();
            // $table->text('product_supplies')->nullable();
            // $table->text('product_parts')->nullable();
            // $table->text('product_components')->nullable();
            // $table->text('product_materials')->nullable();
            // $table->text('product_ingredients')->nullable();
            // $table->text('product_formulations')->nullable();
            // $table->text('product_recipes')->nullable();
            // $table->text('product_directions')->nullable();
            // $table->text('product_tips')->nullable();
            // $table->text('product_tricks')->nullable();
            // $table->text('product_hacks')->nullable();
            // $table->text('product_uses')->nullable();
            // $table->text('product_benefits')->nullable();
            // $table->text('product_features')->nullable();
            // $table->text('product_specifications')->nullable();
            // $table->text('product_dimensions')->nullable();
            // $table->text('product_weight')->nullable();
            // $table->text('product_capacity')->nullable();
            // $table->text('product_volume')->nullable();
            // $table->text('product_size_chart')->nullable();
            // $table->text('product_color_options')->nullable();
            // $table->text('product_style_options')->nullable();
            // $table->text('product_pattern_options')->nullable();
            // $table->text('product_texture_options')->nullable();
            // $table->text('product_finish_options')->nullable();
            // $table->text('product_quality_info')->nullable();
            // $table->text('product_certifications')->nullable();
            // $table->text('product_compliance_info')->nullable();
            // $table->text('product_regulatory_info')->nullable();
            // $table->text('product_safety_info')->nullable();
            // $table->text('product_warranty_info')->nullable();
            // $table->text('product_support_info')->nullable();
            // $table->text('product_maintenance_info')->nullable();
            // $table->text('product_care_info')->nullable();
            // $table->text('product_cleaning_info')->nullable();
            // $table->text('product_storage_info')->nullable();
            // $table->text('product_handling_info')->nullable();
            // $table->text('product_disposal_info')->nullable();
            // $table->text('product_recycling_info')->nullable();
            // $table->text('product_disassembly_info')->nullable();
            // $table->text('product_repair_info')->nullable();
            // $table->text('product_replacement_info')->nullable();
            // $table->text('product_upgrade_info')->nullable();
            // $table->text('product_downgrade_info')->nullable();
            // $table->text('product_customization_info')->nullable();
            // $table->text('product_personalization_info')->nullable();
            // $table->text('product_gifting_info')->nullable();
            // $table->text('product_subscription_options')->nullable();
            // $table->text('product_pre_order_options')->nullable();
            // $table->text('product_back_order_options')->nullable();
            // $table->text('product_limited_edition_info')->nullable();
            // $table->text('product_exclusive_offers')->nullable();
            // $table->text('product_loyalty_program_info')->nullable();
            // $table->text('product_affiliate_program_info')->nullable();
            // $table->text('product_bulk_order_info')->nullable();
            // $table->text('product_wholesale_info')->nullable();
            // $table->text('product_gift_wrapping_info')->nullable();
            // $table->text('product_customization_options')->nullable();
            // $table->text('product_personalization_options')->nullable();
            // $table->text('product_installation_services')->nullable();
            // $table->text('product_financing_options')->nullable();
            // $table->text('product_trade_in_program_info')->nullable();
            // $table->text('product_loyalty_rewards')->nullable();
            // $table->text('product_referral_program_info')->nullable();
            // $table->text('product_customer_support_info')->nullable();
            // $table->text('product_warranty_claim_info')->nullable();
            // $table->text('product_registration_info')->nullable();
            // $table->text('product_recalls')->nullable();
            // $table->text('product_sustainability_info')->nullable();
            // $table->text('product_eco_friendly_certifications')->nullable();
            // $table->text('product_carbon_footprint_info')->nullable();
            // $table->text('product_recycling_program_info')->nullable();
            // $table->text('product_energy_efficiency_info')->nullable();
            // $table->text('product_water_usage_info')->nullable();
            // $table->text('product_supply_chain_transparency')->nullable();
            // $table->text('product_ethical_sourcing_info')->nullable();
            // $table->text('product_community_support_info')->nullable();
            // $table->text('product_charity_partnerships')->nullable();
            // $table->text('product_social_responsibility_info')->nullable();
            // $table->text('product_diversity_inclusion_info')->nullable();
            // $table->text('product_employee_wellbeing_info')->nullable();
            // $table->text('product_customer_feedback')->nullable();
            // $table->text('product_product_updates')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
